version: 0.5.0.{build}
image: Visual Studio 2022
configuration: Release
install:
- ps: |
    Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"
    & "$env:temp\dotnet-install.ps1" -Architecture x64 -Version '8.0.100' -InstallDir "$env:ProgramFiles\dotnet" 
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
nuget:
  account_feed: true
  project_feed: true
build_script:
  - ps: >-
      dotnet build src\creativeminds.cqslight\ -c Release

after_build:
  - ps: >-
      Push-AppveyorArtifact src\creativeminds.cqslight\bin\release\net8.0\*.nupkg
